INSERT INTO `posts_ored` (`id`, `pages`, `categories`, `tags`, `filename`, `detail_name`, `title`, `client`, `description`, `size`, `media_type`, `overstatestyle`, `href`, `index`)
VALUES
	(1,'portfolio home' ,'_all','tag1','CFM_summer2013','folio/cfm_montage','Clickfire Media','','In a constantly evolving transmedia landscape, ClickFire Media puts all the tools along with amazing creative talent under one roof to create rich, innovative experiences.','410x410',3,'','',455),
	(10,'portfolio home','_all mobile','how_to','geicopiggyv3','folio/geicopiggyv3','GEICO Piggy Pinwheels App','The Martin Agency','ClickFire Media created a mobile app for GEICO. The app features Maxwell, GEICO’s signature piggy.','200x200',0,'','',75),
	(11,'portfolio home','_all user_experience social facebook instagram','roxy','roxy_cs','folio/cfm_roxy_cs','Roxy','','Clickfire Media was asked by our client, Digital Brand Architects to create a Facebook based user generated content based contest for ROXY, a leading women\'s action sport apparel company','410x200',0,'','',81),
	(12,'portfolio home','_all social instagram facebook instagram beauty_fashion retail','retail social facebook_apps instagram facebook social','NineWest','folio/nine_west','Nine West','','Challenge: \nClickFireMedia was challenged to create a Facebook app for DBA and their client, Nine West','410x200',0,'','',83),
	(13,'portfolio home','_all social instagram facebook instagram beauty_fashion retail','retail facebook_apps facebook social instagram','limitedv2','folio/the_limited','The Limited','','Challenge: \nClickFireMedia was challenged to create a Facebook app for DBA and their client, The Limited','200x200',0,'','',87),
	(14,'portfolio home','_all',NULL,'tradjenta','folio/tradjenta','Tradjenta',NULL,NULL,'200x200',1,NULL,NULL,521),
	(15,'portfolio home','_all facebook social',NULL,'stride','folio/stride','Stride','JWT','JWT challenged ClickFire Media to create a customized Facebook tab and application for their client, Stride Gum.','200x200',NULL,NULL,NULL,482),
	(16,'portfolio home','_all innovations beauty_fashion facebook featured','facebook_apps other','CS_BCA_APP_V2_Small','folio/bca','Breast Cancer Awareness','','As part of a Breast Cancer Awareness campaign, ClickFire Media was challenged by Digital Brand Architects (DBA) to build a Facebook application that raised awareness for breast cancer','200x200',1,'','',88),
	(17,'portfolio home','_all facebook featured','facebook app','chevysonicv2','folio/chevysonicv2','Chevy Sonic','Big Fuel','Challenge:\nClickFire Media was challenged by Big Fuel to create a unique car customizer Facebook app for their client, Chevrolet for their Sonic car line','410x200',0,'','',254),
	(18,'portfolio home','_all social facebook featured','','samsung_camera','folio/samsung_camera','Samsung Camera','Big Fuel','Challenge: \nClickFire Media was challenged by Big Fuel to create a Facebook application for their client, Samsung','200x200',0,'','',255),
	(19,'portfolio home','_all social facebook retail instagram','facebook_apps','dennys_app','folio/dennys_facebook_app','Denny\'s Facebook App','Gotham','ClickFireMedia was challenged to create a Facebook app, which used the Instagram API, for Gotham and their client, Denny\'s.','410x200',0,'','',265),
	(20,'portfolio home','_all social games facebook','facebook_apps other','SharpAppv4_final','folio/SharpAppv4_final','Sharp AQUOS App','','<h2>My Contribution</h2><p></p><h2>Challenge:</h2><p>In a direct-to-client execution for Sharp AQUOS, Clickfire Media created the ultimate tailgate experience just in time for football season.</p>','200x200',0,'','',289),
	(21,'portfolio home','_all development','dev','ored_skittles','folio/skittles','Skittles.com','Wrigley\'s','Big Spaceship was challenged to create a new website for Wrigley\'s brand, Skittles','200x200',0,'','',269),
	(22,'portfolio home','_all development','dev','ored_starburst1','folio/starburst','Starburst.com','Wrigley\'s','Big Spaceship was challenged to create a new website for Wrigley\'s brand, Starburst','200x200',0,'','',270),
	(23,'portfolio home','_all development user_experience design','dev','ored_nickandcampbell','folio/nickandcampbell','Nick + Campbell','Nick + Campbell','As a freelance project, I created an e-commerce platform from scratch for a boutique fashion brand using the PHP framework, Zend.','200x200',0,'','',272),
	(24,'portfolio home','_all development user_experience design','dev','ored_quickspikes1','folio/quickspikes','Quick Spikes','Quick Spikes','As a freelance project, I created an e-commerce platform for a golf apparel brand using Wordpress.','200x200',0,'','',273),
	(25,'portfolio home','_all games development','dev','ored_parksunleashed','folio/parksunleashed','ZYRTEC Parks Unleashed','JWT','I led a team of flash developers in the creation of a series of mini games.','200x200',0,'','',275),
	(26,"portfolio home","_all development design user_experience","tag1 tag2",'ICUinParis',  "folio/icu","ICUINPARIS","ICUinParis","ICU's mission is to provide independent designers with an interactive online platform to sell their work and grow their brands.","410x410",0,"half","",108),
	(27,"portfolio home","_all development","tag1 tag2",'ored_smirnoff',  "folio/smirnoff","Smirnoff Nightlife Exchange Project","JWT","We created a large projection 3D installion piece as part of the campaign to be shown at the parties.","200x200",0,"half","",109),
	
	(514,'_all home','_all','tag1 tag2','7_Code','folio/7_Code','CODE.ORG','','Click 3X partnered with director, Lesley Chilcott, on Code Stars - a short film promoting Code.org','200x200',0,'half','',471),

	(100,'about_me','_all interactive','','owen','about/owen_corso','I Am Owen Corso','Lead Technologist','<p>A veteran of the agency world, Owen joins the Click family to help strategically position the technology at the forefront finding innovative solutions to the diverse challenges of our clients','410x200',0,'half fixed light seethrough','',401),
	(200,'about_me','_all','tag1','ored-music','about/ored_music','I Like to Rock',NULL,'I like to rock.','410x200',0,'half fixed light seethrough',NULL,523),
	(201,'about_me','_all','tag1 tag2','ored-working','about/ored_code','I Write Code','','I am work at the intersection of technology and marketing.','410x200',0,'half fixed light seethrough','',454),
	(202,'about_me','_all','tag1 tag2','ored-lax','about/ored_lax','I Play Lacrosse','','For the last 20 years, I\'ve played mens lacrosse at all levels of competition.','410x200',0,'half fixed light seethrough','',453),
	(203,'about_me','_all',NULL,'about_who_we_are','about/clickfire_media','I Work at Clickfire Media',NULL,'In a constantly evolving landscape, ClickFire Media puts all the tools along with amazing creative and technology talent under one roof. ','410x200',3,'half fixed light seethrough',NULL,489),

	(401,'portfolio home music ','_all music ',NULL,'ored_redmachine','music/i-wont-let-you-down','I Won\'t Let You Down',"Red Machine",'I relatively recent tune I wrote with Red Machine is an acoustically driven folk rock melody.','200x200',0,NULL,NULL,505),
	(402,'portfolio home music ','_all music ',NULL,'ored_lll','music/jons_song_video',"Jon\'s Song","The Good News","A music video I made using my brother\'s footage from his honeymoon",'200x200',0,NULL,NULL,506),
	(403,'portfolio home music ','_all music ',NULL,'ored_jamwithtoast2','music/jamwithtoast',"Battle of the Ad Bands","JWT","During Agency Week, I got some colleages together and won Battle of the Ad Bands",'200x200',0,NULL,NULL,507),

	(500,'contact','_all','tag1 tag2','ored_contact_map','','Post','Client','','830x410',0,'none','http://bit.ly/14BUm7f',457),
	(502,'contact','_all','tag1 tag2','ored_mail','','Feel free to email me','Anytime','','410x200',0,'half fixed light','mailto:owen@ored.net',459),
	(503,'contact','_all','tag1 tag2','ored_contact_map_small','','410 East 13th Street','New York, NY 10003','p:201.602.0069','410x200',0,'half fixed light','http://bit.ly/14BUm7f',458);
